Discriminant Function Analysis 
========================================================

Linear Discriminant Analysis with Jacknifed Prediction
-------------------------------------------------------
```{r}
library(MASS)
mydata <- iris

fit <- lda(Species ~ Sepal.Length + Sepal.Width + Petal.Length, data=mydata,
   na.action="na.omit", CV=TRUE)
fit
```
Assess the accuracy of the prediction percent correct for each category of G

```{r}
ct <- table(mydata$Species, fit$class)
diag(prop.table(ct, 1))
```
total percent correct
```{r}
sum(diag(prop.table(ct)))
```

** To Do: do a MANOVA for significance test. ** 

Quadratic Discriminant Function
-------------------------------

Quadratic Discriminant Analysis with 3 groups applying resubstitution prediction and equal prior probabilities.
```{r}
fit <- qda(Species ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width, data=na.omit(mydata), prior=c(1,1,1)/3)
fit
ct <- table(mydata$Species, fit$class)
diag(prop.table(ct, 1))
#total percent correct
sum(diag(prop.table(ct)))
```

Visualizing the Results
-----------------------
Scatter plot using the 1st two discriminant dimensions

```{r}
plot(fit) # fit from lda ??? did not work
# Panels of histograms and overlayed density plots
# for 1st discriminant function
plot(fit, dimen=1, type="both") # fit from lda 
```
